# Default values for param-sweep.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: wbuchwalter/helm-tf
  tag: hyper-param-sweep
  pullPolicy: Always
training:
  LearningRateSweep:
    - 0.0001
    - 0.001
    - 0.01
  hiddenLayersSweep:
    - 4
    - 5